<?php

use Illuminate\Database\Seeder;
use App\Citie;

class CitieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = '[
            {"id":"1","department":"1","name":"MEDELLIN","available":"1"},
            {"id":"2","department":"1","name":"ABEJORRAL","available":"1"},
            {"id":"3","department":"1","name":"ABRIAQUI","available":"1"},
            {"id":"4","department":"1","name":"ALEJANDRIA","available":"1"},
            {"id":"5","department":"1","name":"AMAGA","available":"1"},
            {"id":"6","department":"1","name":"AMALFI","available":"1"},
            {"id":"7","department":"1","name":"ANDES","available":"1"},
            {"id":"8","department":"1","name":"ANGELOPOLIS","available":"1"},
            {"id":"9","department":"1","name":"ANGOSTURA","available":"1"},
            {"id":"10","department":"1","name":"ANORI","available":"1"},
            {"id":"11","department":"1","name":"SANTAFE DE ANTIOQUIA","available":"1"},
            {"id":"12","department":"1","name":"ANZA","available":"1"},
            {"id":"13","department":"1","name":"APARTADO","available":"1"},
            {"id":"14","department":"1","name":"ARBOLETES","available":"1"},
            {"id":"15","department":"1","name":"ARGELIA","available":"1"},
            {"id":"16","department":"1","name":"ARMENIA","available":"1"},
            {"id":"17","department":"1","name":"BARBOSA","available":"1"},
            {"id":"18","department":"1","name":"BELMIRA","available":"1"},
            {"id":"19","department":"1","name":"BELLO","available":"1"},
            {"id":"20","department":"1","name":"BETANIA","available":"1"},
            {"id":"21","department":"1","name":"BETULIA","available":"1"},
            {"id":"22","department":"1","name":"CIUDAD BOLIVAR","available":"1"},
            {"id":"23","department":"1","name":"BRICEÑO","available":"1"},
            {"id":"24","department":"1","name":"BURITICA","available":"1"},
            {"id":"25","department":"1","name":"CACERES","available":"1"},
            {"id":"26","department":"1","name":"CAICEDO","available":"1"},
            {"id":"27","department":"1","name":"CALDAS","available":"1"},
            {"id":"28","department":"1","name":"CAMPAMENTO","available":"1"},
            {"id":"29","department":"1","name":"CAÑASGORDAS","available":"1"},
            {"id":"30","department":"1","name":"CARACOLI","available":"1"},
            {"id":"31","department":"1","name":"CARAMANTA","available":"1"},
            {"id":"32","department":"1","name":"CAREPA","available":"1"},
            {"id":"33","department":"1","name":"EL CARMEN DE VIBORAL","available":"1"},
            {"id":"34","department":"1","name":"CAROLINA","available":"1"},
            {"id":"35","department":"1","name":"CAUCASIA","available":"1"},
            {"id":"36","department":"1","name":"CHIGORODO","available":"1"},
            {"id":"37","department":"1","name":"CISNEROS","available":"1"},
            {"id":"38","department":"1","name":"COCORNA","available":"1"},
            {"id":"39","department":"1","name":"CONCEPCION","available":"1"},
            {"id":"40","department":"1","name":"CONCORDIA","available":"1"},
            {"id":"41","department":"1","name":"COPACABANA","available":"1"},
            {"id":"42","department":"1","name":"DABEIBA","available":"1"},
            {"id":"43","department":"1","name":"DON MATIAS","available":"1"},
            {"id":"44","department":"1","name":"EBEJICO","available":"1"},
            {"id":"45","department":"1","name":"EL BAGRE","available":"1"},
            {"id":"46","department":"1","name":"ENTRERRIOS","available":"1"},
            {"id":"47","department":"1","name":"ENVIGADO","available":"1"},
            {"id":"48","department":"1","name":"FREDONIA","available":"1"},
            {"id":"49","department":"1","name":"FRONTINO","available":"1"},
            {"id":"50","department":"1","name":"GIRALDO","available":"1"},
            {"id":"51","department":"1","name":"GIRARDOTA","available":"1"},
            {"id":"52","department":"1","name":"GOMEZ PLATA","available":"1"},
            {"id":"53","department":"1","name":"GRANADA","available":"1"},
            {"id":"54","department":"1","name":"GUADALUPE","available":"1"},
            {"id":"55","department":"1","name":"GUARNE","available":"1"},
            {"id":"56","department":"1","name":"GUATAPE","available":"1"},
            {"id":"57","department":"1","name":"HELICONIA","available":"1"},
            {"id":"58","department":"1","name":"HISPANIA","available":"1"},
            {"id":"59","department":"1","name":"ITAGUI","available":"1"},
            {"id":"60","department":"1","name":"ITUANGO","available":"1"},
            {"id":"61","department":"1","name":"JARDIN","available":"1"},
            {"id":"62","department":"1","name":"JERICO","available":"1"},
            {"id":"63","department":"1","name":"LA CEJA","available":"1"},
            {"id":"64","department":"1","name":"LA ESTRELLA","available":"1"},
            {"id":"65","department":"1","name":"LA PINTADA","available":"1"},
            {"id":"66","department":"1","name":"LA UNION","available":"1"},
            {"id":"67","department":"1","name":"LIBORINA","available":"1"},
            {"id":"68","department":"1","name":"MACEO","available":"1"},
            {"id":"69","department":"1","name":"MARINILLA","available":"1"},
            {"id":"70","department":"1","name":"MONTEBELLO","available":"1"},
            {"id":"71","department":"1","name":"MURINDO","available":"1"},
            {"id":"72","department":"1","name":"MUTATA","available":"1"},
            {"id":"73","department":"1","name":"NARIÑO","available":"1"},
            {"id":"74","department":"1","name":"NECOCLI","available":"1"},
            {"id":"75","department":"1","name":"NECHI","available":"1"},
            {"id":"76","department":"1","name":"OLAYA","available":"1"},
            {"id":"77","department":"1","name":"PEÐOL","available":"1"},
            {"id":"78","department":"1","name":"PEQUE","available":"1"},
            {"id":"79","department":"1","name":"PUEBLORRICO","available":"1"},
            {"id":"80","department":"1","name":"PUERTO BERRIO","available":"1"},
            {"id":"81","department":"1","name":"PUERTO NARE","available":"1"},
            {"id":"82","department":"1","name":"PUERTO TRIUNFO","available":"1"},
            {"id":"83","department":"1","name":"REMEDIOS","available":"1"},
            {"id":"84","department":"1","name":"RETIRO","available":"1"},
            {"id":"85","department":"1","name":"RIONEGRO","available":"1"},
            {"id":"86","department":"1","name":"SABANALARGA","available":"1"},
            {"id":"87","department":"1","name":"SABANETA","available":"1"},
            {"id":"88","department":"1","name":"SALGAR","available":"1"},
            {"id":"89","department":"1","name":"SAN ANDRES DE CUERQUIA","available":"1"},
            {"id":"90","department":"1","name":"SAN CARLOS","available":"1"},
            {"id":"91","department":"1","name":"SAN FRANCISCO","available":"1"},
            {"id":"92","department":"1","name":"SAN JERONIMO","available":"1"},
            {"id":"93","department":"1","name":"SAN JOSE DE LA MONTAÑA","available":"1"},
            {"id":"94","department":"1","name":"SAN JUAN DE URABA","available":"1"},
            {"id":"95","department":"1","name":"SAN LUIS","available":"1"},
            {"id":"96","department":"1","name":"SAN PEDRO","available":"1"},
            {"id":"97","department":"1","name":"SAN PEDRO DE URABA","available":"1"},
            {"id":"98","department":"1","name":"SAN RAFAEL","available":"1"},
            {"id":"99","department":"1","name":"SAN ROQUE","available":"1"},
            {"id":"100","department":"1","name":"SAN VICENTE","available":"1"},
            {"id":"101","department":"1","name":"SANTA BARBARA","available":"1"},
            {"id":"102","department":"1","name":"SANTA ROSA DE OSOS","available":"1"},
            {"id":"103","department":"1","name":"SANTO DOMINGO","available":"1"},
            {"id":"104","department":"1","name":"EL SANTUARIO","available":"1"},
            {"id":"105","department":"1","name":"SEGOVIA","available":"1"},
            {"id":"106","department":"1","name":"SONSON","available":"1"},
            {"id":"107","department":"1","name":"SOPETRAN","available":"1"},
            {"id":"108","department":"1","name":"TAMESIS","available":"1"},
            {"id":"109","department":"1","name":"TARAZA","available":"1"},
            {"id":"110","department":"1","name":"TARSO","available":"1"},
            {"id":"111","department":"1","name":"TITIRIBI","available":"1"},
            {"id":"112","department":"1","name":"TOLEDO","available":"1"},
            {"id":"113","department":"1","name":"TURBO","available":"1"},
            {"id":"114","department":"1","name":"URAMITA","available":"1"},
            {"id":"115","department":"1","name":"URRAO","available":"1"},
            {"id":"116","department":"1","name":"VALDIVIA","available":"1"},
            {"id":"117","department":"1","name":"VALPARAISO","available":"1"},
            {"id":"118","department":"1","name":"VEGACHI","available":"1"},
            {"id":"119","department":"1","name":"VENECIA","available":"1"},
            {"id":"120","department":"1","name":"VIGIA DEL FUERTE","available":"1"},
            {"id":"121","department":"1","name":"YALI","available":"1"},
            {"id":"122","department":"1","name":"YARUMAL","available":"1"},
            {"id":"123","department":"1","name":"YOLOMBO","available":"1"},
            {"id":"124","department":"1","name":"YONDO","available":"1"},
            {"id":"125","department":"1","name":"ZARAGOZA","available":"1"},
            {"id":"126","department":"2","name":"BARRANQUILLA","available":"1"},
            {"id":"127","department":"2","name":"BARANOA","available":"1"},
            {"id":"128","department":"2","name":"CAMPO DE LA CRUZ","available":"1"},
            {"id":"129","department":"2","name":"CANDELARIA","available":"1"},
            {"id":"130","department":"2","name":"GALAPA","available":"1"},
            {"id":"131","department":"2","name":"JUAN DE ACOSTA","available":"1"},
            {"id":"132","department":"2","name":"LURUACO","available":"1"},
            {"id":"133","department":"2","name":"MALAMBO","available":"1"},
            {"id":"134","department":"2","name":"MANATI","available":"1"},
            {"id":"135","department":"2","name":"PALMAR DE VARELA","available":"1"},
            {"id":"136","department":"2","name":"PIOJO","available":"1"},
            {"id":"137","department":"2","name":"POLONUEVO","available":"1"},
            {"id":"138","department":"2","name":"PONEDERA","available":"1"},
            {"id":"139","department":"2","name":"PUERTO COLOMBIA","available":"1"},
            {"id":"140","department":"2","name":"REPELON","available":"1"},
            {"id":"141","department":"2","name":"SABANAGRANDE","available":"1"},
            {"id":"142","department":"2","name":"SABANALARGA","available":"1"},
            {"id":"143","department":"2","name":"SANTA LUCIA","available":"1"},
            {"id":"144","department":"2","name":"SANTO TOMAS","available":"1"},
            {"id":"145","department":"2","name":"SOLEDAD","available":"1"},
            {"id":"146","department":"2","name":"SUAN","available":"1"},
            {"id":"147","department":"2","name":"TUBARA","available":"1"},
            {"id":"148","department":"2","name":"USIACURI","available":"1"},
            {"id":"149","department":"3","name":"BOGOTA, D.C.\r\n","available":"1"},
            {"id":"150","department":"4","name":"MAHATES","available":"1"},
            {"id":"151","department":"4","name":"MARGARITA","available":"1"},
            {"id":"152","department":"4","name":"MARIA LA BAJA","available":"1"},
            {"id":"153","department":"4","name":"MONTECRISTO","available":"1"},
            {"id":"154","department":"4","name":"MOMPOS","available":"1"},
            {"id":"155","department":"4","name":"NOROSI","available":"1"},
            {"id":"156","department":"4","name":"MORALES","available":"1"},
            {"id":"157","department":"4","name":"PINILLOS","available":"1"},
            {"id":"158","department":"4","name":"REGIDOR","available":"1"},
            {"id":"159","department":"4","name":"RIO VIEJO","available":"1"},
            {"id":"160","department":"4","name":"SAN CRISTOBAL","available":"1"},
            {"id":"161","department":"4","name":"SAN ESTANISLAO","available":"1"},
            {"id":"162","department":"4","name":"SAN FERNANDO","available":"1"},
            {"id":"163","department":"4","name":"SAN JACINTO","available":"1"},
            {"id":"164","department":"4","name":"SAN JACINTO DEL CAUCA","available":"1"},
            {"id":"165","department":"4","name":"SAN JUAN NEPOMUCENO","available":"1"},
            {"id":"166","department":"4","name":"SAN MARTIN DE LOBA","available":"1"},
            {"id":"167","department":"4","name":"SAN PABLO","available":"1"},
            {"id":"168","department":"4","name":"SANTA CATALINA","available":"1"},
            {"id":"169","department":"4","name":"SANTA ROSA","available":"1"},
            {"id":"170","department":"4","name":"SANTA ROSA DEL SUR","available":"1"},
            {"id":"171","department":"4","name":"SIMITI","available":"1"},
            {"id":"172","department":"4","name":"SOPLAVIENTO","available":"1"},
            {"id":"173","department":"4","name":"TALAIGUA NUEVO","available":"1"},
            {"id":"174","department":"4","name":"TIQUISIO","available":"1"},
            {"id":"175","department":"4","name":"TURBACO","available":"1"},
            {"id":"176","department":"4","name":"TURBANA","available":"1"},
            {"id":"177","department":"4","name":"VILLANUEVA","available":"1"},
            {"id":"178","department":"4","name":"ZAMBRANO","available":"1"},
            {"id":"179","department":"5","name":"TUNJA","available":"1"},
            {"id":"180","department":"5","name":"ALMEIDA","available":"1"},
            {"id":"181","department":"5","name":"AQUITANIA","available":"1"},
            {"id":"182","department":"5","name":"ARCABUCO","available":"1"},
            {"id":"183","department":"5","name":"BELEN","available":"1"},
            {"id":"184","department":"5","name":"BERBEO","available":"1"},
            {"id":"185","department":"5","name":"BETEITIVA","available":"1"},
            {"id":"186","department":"5","name":"BOAVITA","available":"1"},
            {"id":"187","department":"5","name":"BOYACA","available":"1"},
            {"id":"188","department":"5","name":"BRICEÑO","available":"1"},
            {"id":"189","department":"5","name":"BUENAVISTA","available":"1"},
            {"id":"190","department":"5","name":"BUSBANZA","available":"1"},
            {"id":"191","department":"5","name":"CALDAS","available":"1"},
            {"id":"192","department":"5","name":"CAMPOHERMOSO","available":"1"},
            {"id":"193","department":"5","name":"CERINZA","available":"1"},
            {"id":"194","department":"5","name":"CHINAVITA","available":"1"},
            {"id":"195","department":"5","name":"CHIQUINQUIRA","available":"1"},
            {"id":"196","department":"5","name":"CHISCAS","available":"1"},
            {"id":"197","department":"5","name":"CHITA","available":"1"},
            {"id":"198","department":"5","name":"CHITARAQUE","available":"1"},
            {"id":"199","department":"5","name":"CHIVATA","available":"1"},
            {"id":"200","department":"5","name":"CIENEGA","available":"1"},
            {"id":"201","department":"5","name":"COMBITA","available":"1"},
            {"id":"202","department":"5","name":"COPER","available":"1"},
            {"id":"203","department":"5","name":"CORRALES","available":"1"},
            {"id":"204","department":"5","name":"COVARACHIA","available":"1"},
            {"id":"205","department":"5","name":"CUBARA","available":"1"},
            {"id":"206","department":"5","name":"CUCAITA","available":"1"},
            {"id":"207","department":"5","name":"CUITIVA","available":"1"},
            {"id":"208","department":"5","name":"CHIQUIZA","available":"1"},
            {"id":"209","department":"5","name":"CHIVOR","available":"1"},
            {"id":"210","department":"5","name":"DUITAMA","available":"1"},
            {"id":"211","department":"5","name":"EL COCUY","available":"1"},
            {"id":"212","department":"5","name":"EL ESPINO","available":"1"},
            {"id":"213","department":"5","name":"FIRAVITOBA","available":"1"},
            {"id":"214","department":"5","name":"FLORESTA","available":"1"},
            {"id":"215","department":"5","name":"GACHANTIVA","available":"1"},
            {"id":"216","department":"5","name":"GAMEZA","available":"1"},
            {"id":"217","department":"5","name":"GARAGOA","available":"1"},
            {"id":"218","department":"5","name":"GUACAMAYAS","available":"1"},
            {"id":"219","department":"5","name":"GUATEQUE","available":"1"},
            {"id":"220","department":"5","name":"GUAYATA","available":"1"},
            {"id":"221","department":"5","name":"GsICAN","available":"1"},
            {"id":"222","department":"5","name":"IZA","available":"1"},
            {"id":"223","department":"5","name":"JENESANO","available":"1"},
            {"id":"224","department":"5","name":"JERICO","available":"1"},
            {"id":"225","department":"5","name":"LABRANZAGRANDE","available":"1"},
            {"id":"226","department":"5","name":"LA CAPILLA","available":"1"},
            {"id":"227","department":"5","name":"LA VICTORIA","available":"1"},
            {"id":"228","department":"5","name":"LA UVITA","available":"1"},
            {"id":"229","department":"5","name":"VILLA DE LEYVA","available":"1"},
            {"id":"230","department":"5","name":"MACANAL","available":"1"},
            {"id":"231","department":"5","name":"MARIPI","available":"1"},
            {"id":"232","department":"5","name":"MIRAFLORES","available":"1"},
            {"id":"233","department":"5","name":"MONGUA","available":"1"},
            {"id":"234","department":"5","name":"MONGUI","available":"1"},
            {"id":"235","department":"5","name":"MONIQUIRA","available":"1"},
            {"id":"236","department":"5","name":"MOTAVITA","available":"1"},
            {"id":"237","department":"5","name":"MUZO","available":"1"},
            {"id":"238","department":"5","name":"NOBSA","available":"1"},
            {"id":"239","department":"5","name":"NUEVO COLON","available":"1"},
            {"id":"240","department":"5","name":"OICATA","available":"1"},
            {"id":"241","department":"5","name":"OTANCHE","available":"1"},
            {"id":"242","department":"5","name":"PACHAVITA","available":"1"},
            {"id":"243","department":"5","name":"PAEZ","available":"1"},
            {"id":"244","department":"5","name":"PAIPA","available":"1"},
            {"id":"245","department":"5","name":"PAJARITO","available":"1"},
            {"id":"246","department":"5","name":"PANQUEBA","available":"1"},
            {"id":"247","department":"5","name":"PAUNA","available":"1"},
            {"id":"248","department":"5","name":"PAYA","available":"1"},
            {"id":"249","department":"5","name":"PAZ DE RIO","available":"1"},
            {"id":"250","department":"5","name":"PESCA","available":"1"},
            {"id":"251","department":"5","name":"PISBA","available":"1"},
            {"id":"252","department":"5","name":"PUERTO BOYACA","available":"1"},
            {"id":"253","department":"5","name":"QUIPAMA","available":"1"},
            {"id":"254","department":"5","name":"RAMIRIQUI","available":"1"},
            {"id":"255","department":"5","name":"RAQUIRA","available":"1"},
            {"id":"256","department":"5","name":"RONDON","available":"1"},
            {"id":"257","department":"5","name":"SABOYA","available":"1"},
            {"id":"258","department":"5","name":"SACHICA","available":"1"},
            {"id":"259","department":"5","name":"SAMACA","available":"1"},
            {"id":"260","department":"5","name":"SAN EDUARDO","available":"1"},
            {"id":"261","department":"5","name":"SAN JOSE DE PARE","available":"1"},
            {"id":"262","department":"5","name":"SAN LUIS DE GACENO","available":"1"},
            {"id":"263","department":"5","name":"SAN MATEO","available":"1"},
            {"id":"264","department":"5","name":"SAN MIGUEL DE SEMA","available":"1"},
            {"id":"265","department":"5","name":"SAN PABLO DE BORBUR","available":"1"},
            {"id":"266","department":"5","name":"SANTANA","available":"1"},
            {"id":"267","department":"5","name":"SANTA MARIA","available":"1"},
            {"id":"268","department":"5","name":"SANTA ROSA DE VITERBO","available":"1"},
            {"id":"269","department":"5","name":"SANTA SOFIA","available":"1"},
            {"id":"270","department":"5","name":"SATIVANORTE","available":"1"},
            {"id":"271","department":"5","name":"SATIVASUR","available":"1"},
            {"id":"272","department":"5","name":"SIACHOQUE","available":"1"},
            {"id":"273","department":"5","name":"SOATA","available":"1"},
            {"id":"274","department":"5","name":"SOCOTA","available":"1"},
            {"id":"275","department":"5","name":"SOCHA","available":"1"},
            {"id":"276","department":"5","name":"SOGAMOSO","available":"1"},
            {"id":"277","department":"5","name":"SOMONDOCO","available":"1"},
            {"id":"278","department":"5","name":"SORA","available":"1"},
            {"id":"279","department":"5","name":"SOTAQUIRA","available":"1"},
            {"id":"280","department":"5","name":"SORACA","available":"1"},
            {"id":"281","department":"5","name":"SUSACON","available":"1"},
            {"id":"282","department":"5","name":"SUTAMARCHAN","available":"1"},
            {"id":"283","department":"5","name":"SUTATENZA","available":"1"},
            {"id":"284","department":"5","name":"TASCO","available":"1"},
            {"id":"285","department":"5","name":"TENZA","available":"1"},
            {"id":"286","department":"5","name":"TIBANA","available":"1"},
            {"id":"287","department":"5","name":"TIBASOSA","available":"1"},
            {"id":"288","department":"5","name":"TINJACA","available":"1"},
            {"id":"289","department":"5","name":"TIPACOQUE","available":"1"},
            {"id":"290","department":"5","name":"TOCA","available":"1"},
            {"id":"291","department":"5","name":"TOGsI","available":"1"},
            {"id":"292","department":"5","name":"TOPAGA","available":"1"},
            {"id":"293","department":"5","name":"TOTA","available":"1"},
            {"id":"294","department":"5","name":"TUNUNGUA","available":"1"},
            {"id":"295","department":"5","name":"TURMEQUE","available":"1"},
            {"id":"296","department":"5","name":"TUTA","available":"1"},
            {"id":"297","department":"5","name":"TUTAZA","available":"1"},
            {"id":"298","department":"5","name":"UMBITA","available":"1"},
            {"id":"299","department":"5","name":"VENTAQUEMADA","available":"1"},
            {"id":"300","department":"5","name":"VIRACACHA","available":"1"},
            {"id":"301","department":"5","name":"ZETAQUIRA","available":"1"},
            {"id":"302","department":"6","name":"MANIZALES","available":"1"},
            {"id":"303","department":"6","name":"AGUADAS","available":"1"},
            {"id":"304","department":"6","name":"ANSERMA","available":"1"},
            {"id":"305","department":"6","name":"ARANZAZU","available":"1"},
            {"id":"306","department":"6","name":"BELALCAZAR","available":"1"},
            {"id":"307","department":"6","name":"CHINCHINA","available":"1"},
            {"id":"308","department":"6","name":"FILADELFIA","available":"1"},
            {"id":"309","department":"6","name":"LA DORADA","available":"1"},
            {"id":"310","department":"6","name":"LA MERCED","available":"1"},
            {"id":"311","department":"6","name":"MANZANARES","available":"1"},
            {"id":"312","department":"6","name":"MARMATO","available":"1"},
            {"id":"313","department":"6","name":"MARQUETALIA","available":"1"},
            {"id":"314","department":"6","name":"MARULANDA","available":"1"},
            {"id":"315","department":"6","name":"NEIRA","available":"1"},
            {"id":"316","department":"6","name":"NORCASIA","available":"1"},
            {"id":"317","department":"6","name":"PACORA","available":"1"},
            {"id":"318","department":"6","name":"PALESTINA","available":"1"},
            {"id":"319","department":"6","name":"PENSILVANIA","available":"1"},
            {"id":"320","department":"6","name":"RIOSUCIO","available":"1"},
            {"id":"321","department":"6","name":"RISARALDA","available":"1"},
            {"id":"322","department":"6","name":"SALAMINA","available":"1"},
            {"id":"323","department":"6","name":"SAMANA","available":"1"},
            {"id":"324","department":"6","name":"SAN JOSE","available":"1"},
            {"id":"325","department":"6","name":"SUPIA","available":"1"},
            {"id":"326","department":"6","name":"VICTORIA","available":"1"},
            {"id":"327","department":"6","name":"VILLAMARIA","available":"1"},
            {"id":"328","department":"6","name":"VITERBO","available":"1"},
            {"id":"329","department":"7","name":"FLORENCIA","available":"1"},
            {"id":"330","department":"7","name":"ALBANIA","available":"1"},
            {"id":"331","department":"7","name":"BELEN DE LOS ANDAQUIES","available":"1"},
            {"id":"332","department":"7","name":"CARTAGENA DEL CHAIRA","available":"1"},
            {"id":"333","department":"7","name":"CURILLO","available":"1"},
            {"id":"334","department":"7","name":"EL DONCELLO","available":"1"},
            {"id":"335","department":"7","name":"EL PAUJIL","available":"1"},
            {"id":"336","department":"7","name":"LA MONTAÑITA","available":"1"},
            {"id":"337","department":"7","name":"MILAN","available":"1"},
            {"id":"338","department":"7","name":"MORELIA","available":"1"},
            {"id":"339","department":"7","name":"PUERTO RICO","available":"1"},
            {"id":"340","department":"7","name":"SAN JOSE DEL FRAGUA","available":"1"},
            {"id":"341","department":"7","name":"SAN VICENTE DEL CAGUAN","available":"1"},
            {"id":"342","department":"7","name":"SOLANO","available":"1"},
            {"id":"343","department":"7","name":"SOLITA","available":"1"},
            {"id":"344","department":"7","name":"VALPARAISO","available":"1"},
            {"id":"345","department":"8","name":"POPAYAN","available":"1"},
            {"id":"346","department":"8","name":"ALMAGUER","available":"1"},
            {"id":"347","department":"8","name":"ARGELIA","available":"1"},
            {"id":"348","department":"8","name":"BALBOA","available":"1"},
            {"id":"349","department":"8","name":"BOLIVAR","available":"1"},
            {"id":"350","department":"8","name":"BUENOS AIRES","available":"1"},
            {"id":"351","department":"8","name":"CAJIBIO","available":"1"},
            {"id":"352","department":"8","name":"CALDONO","available":"1"},
            {"id":"353","department":"8","name":"CALOTO","available":"1"},
            {"id":"354","department":"8","name":"CORINTO","available":"1"},
            {"id":"355","department":"8","name":"EL TAMBO","available":"1"},
            {"id":"356","department":"8","name":"FLORENCIA","available":"1"},
            {"id":"357","department":"8","name":"GUACHENE","available":"1"},
            {"id":"358","department":"8","name":"GUAPI","available":"1"},
            {"id":"359","department":"8","name":"INZA","available":"1"},
            {"id":"360","department":"8","name":"JAMBALO","available":"1"},
            {"id":"361","department":"8","name":"LA SIERRA","available":"1"},
            {"id":"362","department":"8","name":"LA VEGA","available":"1"},
            {"id":"363","department":"8","name":"LOPEZ","available":"1"},
            {"id":"364","department":"8","name":"MERCADERES","available":"1"},
            {"id":"365","department":"8","name":"MIRANDA","available":"1"},
            {"id":"366","department":"8","name":"MORALES","available":"1"},
            {"id":"367","department":"8","name":"PADILLA","available":"1"},
            {"id":"368","department":"8","name":"PAEZ","available":"1"},
            {"id":"369","department":"8","name":"PATIA","available":"1"},
            {"id":"370","department":"8","name":"PIAMONTE","available":"1"},
            {"id":"371","department":"8","name":"PIENDAMO","available":"1"},
            {"id":"372","department":"8","name":"PUERTO TEJADA","available":"1"},
            {"id":"373","department":"8","name":"PURACE","available":"1"},
            {"id":"374","department":"8","name":"ROSAS","available":"1"},
            {"id":"375","department":"8","name":"SAN SEBASTIAN","available":"1"},
            {"id":"376","department":"8","name":"SANTANDER DE QUILICHAO","available":"1"},
            {"id":"377","department":"8","name":"SANTA ROSA","available":"1"},
            {"id":"378","department":"8","name":"SILVIA","available":"1"},
            {"id":"379","department":"8","name":"SOTARA","available":"1"},
            {"id":"380","department":"8","name":"SUAREZ","available":"1"},
            {"id":"381","department":"8","name":"SUCRE","available":"1"},
            {"id":"382","department":"8","name":"TIMBIO","available":"1"},
            {"id":"383","department":"8","name":"TIMBIQUI","available":"1"},
            {"id":"384","department":"8","name":"TORIBIO","available":"1"},
            {"id":"385","department":"8","name":"TOTORO","available":"1"},
            {"id":"386","department":"8","name":"VILLA RICA","available":"1"},
            {"id":"387","department":"9","name":"VALLEDUPAR","available":"1"},
            {"id":"388","department":"9","name":"AGUACHICA","available":"1"},
            {"id":"389","department":"9","name":"AGUSTIN CODAZZI","available":"1"},
            {"id":"390","department":"9","name":"ASTREA","available":"1"},
            {"id":"391","department":"9","name":"BECERRIL","available":"1"},
            {"id":"392","department":"9","name":"BOSCONIA","available":"1"},
            {"id":"393","department":"9","name":"CHIMICHAGUA","available":"1"},
            {"id":"394","department":"9","name":"CHIRIGUANA","available":"1"},
            {"id":"395","department":"9","name":"CURUMANI","available":"1"},
            {"id":"396","department":"9","name":"EL COPEY","available":"1"},
            {"id":"397","department":"9","name":"EL PASO","available":"1"},
            {"id":"398","department":"9","name":"GAMARRA","available":"1"},
            {"id":"399","department":"9","name":"GONZALEZ","available":"1"},
            {"id":"400","department":"9","name":"LA GLORIA","available":"1"},
            {"id":"401","department":"9","name":"LA JAGUA DE IBIRICO","available":"1"},
            {"id":"402","department":"9","name":"MANAURE","available":"1"},
            {"id":"403","department":"9","name":"PAILITAS","available":"1"},
            {"id":"404","department":"9","name":"PELAYA","available":"1"},
            {"id":"405","department":"9","name":"PUEBLO BELLO","available":"1"},
            {"id":"406","department":"9","name":"RIO DE ORO","available":"1"},
            {"id":"407","department":"9","name":"LA PAZ","available":"1"},
            {"id":"408","department":"9","name":"SAN ALBERTO","available":"1"},
            {"id":"409","department":"9","name":"SAN DIEGO","available":"1"},
            {"id":"410","department":"9","name":"SAN MARTIN","available":"1"},
            {"id":"411","department":"9","name":"TAMALAMEQUE","available":"1"},
            {"id":"412","department":"10","name":"MONTERIA","available":"1"},
            {"id":"413","department":"10","name":"AYAPEL","available":"1"},
            {"id":"414","department":"10","name":"BUENAVISTA","available":"1"},
            {"id":"415","department":"10","name":"CANALETE","available":"1"},
            {"id":"416","department":"10","name":"CERETE","available":"1"},
            {"id":"417","department":"10","name":"CHIMA","available":"1"},
            {"id":"418","department":"10","name":"CHINU","available":"1"},
            {"id":"419","department":"10","name":"CIENAGA DE ORO","available":"1"},
            {"id":"420","department":"10","name":"COTORRA","available":"1"},
            {"id":"421","department":"10","name":"LA APARTADA","available":"1"},
            {"id":"422","department":"10","name":"LORICA","available":"1"},
            {"id":"423","department":"10","name":"LOS CORDOBAS","available":"1"},
            {"id":"424","department":"10","name":"MOMIL","available":"1"},
            {"id":"425","department":"10","name":"MONTELIBANO","available":"1"},
            {"id":"426","department":"10","name":"MOÑITOS","available":"1"},
            {"id":"427","department":"10","name":"PLANETA RICA","available":"1"},
            {"id":"428","department":"10","name":"PUEBLO NUEVO","available":"1"},
            {"id":"429","department":"10","name":"PUERTO ESCONDIDO","available":"1"},
            {"id":"430","department":"10","name":"PUERTO LIBERTADOR","available":"1"},
            {"id":"431","department":"10","name":"PURISIMA","available":"1"},
            {"id":"432","department":"10","name":"SAHAGUN","available":"1"},
            {"id":"433","department":"10","name":"SAN ANDRES SOTAVENTO","available":"1"},
            {"id":"434","department":"10","name":"SAN ANTERO","available":"1"},
            {"id":"435","department":"10","name":"SAN BERNARDO DEL VIENTO","available":"1"},
            {"id":"436","department":"10","name":"SAN CARLOS","available":"1"},
            {"id":"437","department":"10","name":"SAN PELAYO","available":"1"},
            {"id":"438","department":"10","name":"TIERRALTA","available":"1"},
            {"id":"439","department":"10","name":"VALENCIA","available":"1"},
            {"id":"440","department":"11","name":"AGUA DE DIOS","available":"1"},
            {"id":"441","department":"11","name":"ALBAN","available":"1"},
            {"id":"442","department":"11","name":"ANAPOIMA","available":"1"},
            {"id":"443","department":"11","name":"ANOLAIMA","available":"1"},
            {"id":"444","department":"11","name":"ARBELAEZ","available":"1"},
            {"id":"445","department":"11","name":"BELTRAN","available":"1"},
            {"id":"446","department":"11","name":"BITUIMA","available":"1"},
            {"id":"447","department":"11","name":"BOJACA","available":"1"},
            {"id":"448","department":"11","name":"CABRERA","available":"1"},
            {"id":"449","department":"11","name":"CACHIPAY","available":"1"},
            {"id":"450","department":"11","name":"CAJICA","available":"1"},
            {"id":"451","department":"11","name":"CAPARRAPI","available":"1"},
            {"id":"452","department":"11","name":"CAQUEZA","available":"1"},
            {"id":"453","department":"11","name":"CARMEN DE CARUPA","available":"1"},
            {"id":"454","department":"11","name":"CHAGUANI","available":"1"},
            {"id":"455","department":"11","name":"CHIA","available":"1"},
            {"id":"456","department":"11","name":"CHIPAQUE","available":"1"},
            {"id":"457","department":"11","name":"CHOACHI","available":"1"},
            {"id":"458","department":"11","name":"CHOCONTA","available":"1"},
            {"id":"459","department":"11","name":"COGUA","available":"1"},
            {"id":"460","department":"11","name":"COTA","available":"1"},
            {"id":"461","department":"11","name":"CUCUNUBA","available":"1"},
            {"id":"462","department":"11","name":"EL COLEGIO","available":"1"},
            {"id":"463","department":"11","name":"EL PEÑON","available":"1"},
            {"id":"464","department":"11","name":"EL ROSAL","available":"1"},
            {"id":"465","department":"11","name":"FACATATIVA","available":"1"},
            {"id":"466","department":"11","name":"FOMEQUE","available":"1"},
            {"id":"467","department":"11","name":"FOSCA","available":"1"},
            {"id":"468","department":"11","name":"FUNZA","available":"1"},
            {"id":"469","department":"11","name":"FUQUENE","available":"1"},
            {"id":"470","department":"11","name":"FUSAGASUGA","available":"1"},
            {"id":"471","department":"11","name":"GACHALA","available":"1"},
            {"id":"472","department":"11","name":"GACHANCIPA","available":"1"},
            {"id":"473","department":"11","name":"GACHETA","available":"1"},
            {"id":"474","department":"11","name":"GAMA","available":"1"},
            {"id":"475","department":"11","name":"GIRARDOT","available":"1"},
            {"id":"476","department":"11","name":"GRANADA","available":"1"},
            {"id":"477","department":"11","name":"GUACHETA","available":"1"},
            {"id":"478","department":"11","name":"GUADUAS","available":"1"},
            {"id":"479","department":"11","name":"GUASCA","available":"1"},
            {"id":"480","department":"11","name":"GUATAQUI","available":"1"},
            {"id":"481","department":"11","name":"GUATAVITA","available":"1"},
            {"id":"482","department":"11","name":"GUAYABAL DE SIQUIMA","available":"1"},
            {"id":"483","department":"11","name":"GUAYABETAL","available":"1"},
            {"id":"484","department":"11","name":"GUTIERREZ","available":"1"},
            {"id":"485","department":"11","name":"JERUSALEN","available":"1"},
            {"id":"486","department":"11","name":"JUNIN","available":"1"},
            {"id":"487","department":"11","name":"LA CALERA","available":"1"},
            {"id":"488","department":"11","name":"LA MESA","available":"1"},
            {"id":"489","department":"11","name":"LA PALMA","available":"1"},
            {"id":"490","department":"11","name":"LA PEÑA","available":"1"},
            {"id":"491","department":"11","name":"LA VEGA","available":"1"},
            {"id":"492","department":"11","name":"LENGUAZAQUE","available":"1"},
            {"id":"493","department":"11","name":"MACHETA","available":"1"},
            {"id":"494","department":"11","name":"MADRID","available":"1"},
            {"id":"495","department":"11","name":"MANTA","available":"1"},
            {"id":"496","department":"11","name":"MEDINA","available":"1"},
            {"id":"497","department":"11","name":"MOSQUERA","available":"1"},
            {"id":"498","department":"11","name":"NARIÑO","available":"1"},
            {"id":"499","department":"11","name":"NEMOCON","available":"1"},
            {"id":"500","department":"11","name":"NILO","available":"1"},
            {"id":"501","department":"11","name":"NIMAIMA","available":"1"},
            {"id":"502","department":"11","name":"NOCAIMA","available":"1"},
            {"id":"503","department":"11","name":"VENECIA","available":"1"},
            {"id":"504","department":"11","name":"PACHO","available":"1"},
            {"id":"505","department":"11","name":"PAIME","available":"1"},
            {"id":"506","department":"11","name":"PANDI","available":"1"},
            {"id":"507","department":"11","name":"PARATEBUENO","available":"1"},
            {"id":"508","department":"11","name":"PASCA","available":"1"},
            {"id":"509","department":"11","name":"PUERTO SALGAR","available":"1"},
            {"id":"510","department":"11","name":"PULI","available":"1"},
            {"id":"511","department":"11","name":"QUEBRADANEGRA","available":"1"},
            {"id":"512","department":"11","name":"QUETAME","available":"1"},
            {"id":"513","department":"11","name":"QUIPILE","available":"1"},
            {"id":"514","department":"11","name":"APULO","available":"1"},
            {"id":"515","department":"11","name":"RICAURTE","available":"1"},
            {"id":"516","department":"11","name":"SAN ANTONIO DEL TEQUENDAMA","available":"1"},
            {"id":"517","department":"11","name":"SAN BERNARDO","available":"1"},
            {"id":"518","department":"11","name":"SAN CAYETANO","available":"1"},
            {"id":"519","department":"11","name":"SAN FRANCISCO","available":"1"},
            {"id":"520","department":"11","name":"SAN JUAN DE RIO SECO","available":"1"},
            {"id":"521","department":"11","name":"SASAIMA","available":"1"},
            {"id":"522","department":"11","name":"SESQUILE","available":"1"},
            {"id":"523","department":"11","name":"SIBATE","available":"1"},
            {"id":"524","department":"11","name":"SILVANIA","available":"1"},
            {"id":"525","department":"11","name":"SIMIJACA","available":"1"},
            {"id":"526","department":"11","name":"SOACHA","available":"1"},
            {"id":"527","department":"11","name":"SOPO","available":"1"},
            {"id":"528","department":"11","name":"SUBACHOQUE","available":"1"},
            {"id":"529","department":"11","name":"SUESCA","available":"1"},
            {"id":"530","department":"11","name":"SUPATA","available":"1"},
            {"id":"531","department":"11","name":"SUSA","available":"1"},
            {"id":"532","department":"11","name":"SUTATAUSA","available":"1"},
            {"id":"533","department":"11","name":"TABIO","available":"1"},
            {"id":"534","department":"11","name":"TAUSA","available":"1"},
            {"id":"535","department":"11","name":"TENA","available":"1"},
            {"id":"536","department":"11","name":"TENJO","available":"1"},
            {"id":"537","department":"11","name":"TIBACUY","available":"1"},
            {"id":"538","department":"11","name":"TIBIRITA","available":"1"},
            {"id":"539","department":"11","name":"TOCAIMA","available":"1"},
            {"id":"540","department":"11","name":"TOCANCIPA","available":"1"},
            {"id":"541","department":"11","name":"TOPAIPI","available":"1"},
            {"id":"542","department":"11","name":"UBALA","available":"1"},
            {"id":"543","department":"11","name":"UBAQUE","available":"1"},
            {"id":"544","department":"11","name":"VILLA DE SAN DIEGO DE UBATE","available":"1"},
            {"id":"545","department":"11","name":"UNE","available":"1"},
            {"id":"546","department":"11","name":"UTICA","available":"1"},
            {"id":"547","department":"11","name":"VERGARA","available":"1"},
            {"id":"548","department":"11","name":"VIANI","available":"1"},
            {"id":"549","department":"11","name":"VILLAGOMEZ","available":"1"},
            {"id":"550","department":"11","name":"VILLAPINZON","available":"1"},
            {"id":"551","department":"11","name":"VILLETA","available":"1"},
            {"id":"552","department":"11","name":"VIOTA","available":"1"},
            {"id":"553","department":"11","name":"YACOPI","available":"1"},
            {"id":"554","department":"11","name":"ZIPACON","available":"1"},
            {"id":"555","department":"11","name":"ZIPAQUIRA","available":"1"},
            {"id":"556","department":"12","name":"QUIBDO","available":"1"},
            {"id":"557","department":"12","name":"ACANDI","available":"1"},
            {"id":"558","department":"12","name":"ALTO BAUDO","available":"1"},
            {"id":"559","department":"12","name":"ATRATO","available":"1"},
            {"id":"560","department":"12","name":"BAGADO","available":"1"},
            {"id":"561","department":"12","name":"BAHIA SOLANO","available":"1"},
            {"id":"562","department":"12","name":"BAJO BAUDO","available":"1"},
            {"id":"563","department":"12","name":"BOJAYA","available":"1"},
            {"id":"564","department":"12","name":"EL CANTON DEL SAN PABLO","available":"1"},
            {"id":"565","department":"12","name":"CARMEN DEL DARIEN","available":"1"},
            {"id":"566","department":"12","name":"CERTEGUI","available":"1"},
            {"id":"567","department":"12","name":"CONDOTO","available":"1"},
            {"id":"568","department":"12","name":"EL CARMEN DE ATRATO","available":"1"},
            {"id":"569","department":"12","name":"EL LITORAL DEL SAN JUAN","available":"1"},
            {"id":"570","department":"12","name":"ISTMINA","available":"1"},
            {"id":"571","department":"12","name":"JURADO","available":"1"},
            {"id":"572","department":"12","name":"LLORO","available":"1"},
            {"id":"573","department":"12","name":"MEDIO ATRATO","available":"1"},
            {"id":"574","department":"12","name":"MEDIO BAUDO","available":"1"},
            {"id":"575","department":"12","name":"MEDIO SAN JUAN","available":"1"},
            {"id":"576","department":"12","name":"NOVITA","available":"1"},
            {"id":"577","department":"12","name":"NUQUI","available":"1"},
            {"id":"578","department":"12","name":"RIO IRO","available":"1"},
            {"id":"579","department":"12","name":"RIO QUITO","available":"1"},
            {"id":"580","department":"12","name":"RIOSUCIO","available":"1"},
            {"id":"581","department":"12","name":"SAN JOSE DEL PALMAR","available":"1"},
            {"id":"582","department":"12","name":"SIPI","available":"1"},
            {"id":"583","department":"12","name":"TADO","available":"1"},
            {"id":"584","department":"12","name":"UNGUIA","available":"1"},
            {"id":"585","department":"12","name":"UNION PANAMERICANA","available":"1"},
            {"id":"588","department":"13","name":"NEIVA","available":"1"},
            {"id":"589","department":"13","name":"ACEVEDO","available":"1"},
            {"id":"590","department":"13","name":"AGRADO","available":"1"},
            {"id":"591","department":"13","name":"AIPE","available":"1"},
            {"id":"592","department":"13","name":"ALGECIRAS","available":"1"},
            {"id":"593","department":"13","name":"ALTAMIRA","available":"1"},
            {"id":"594","department":"13","name":"BARAYA","available":"1"},
            {"id":"595","department":"13","name":"CAMPOALEGRE","available":"1"},
            {"id":"596","department":"13","name":"COLOMBIA","available":"1"},
            {"id":"597","department":"13","name":"ELIAS","available":"1"},
            {"id":"598","department":"13","name":"GARZON","available":"1"},
            {"id":"599","department":"13","name":"GIGANTE","available":"1"},
            {"id":"600","department":"13","name":"GUADALUPE","available":"1"},
            {"id":"601","department":"13","name":"HOBO","available":"1"},
            {"id":"602","department":"13","name":"IQUIRA","available":"1"},
            {"id":"603","department":"13","name":"ISNOS","available":"1"},
            {"id":"604","department":"13","name":"LA ARGENTINA","available":"1"},
            {"id":"605","department":"13","name":"LA PLATA","available":"1"},
            {"id":"606","department":"13","name":"NATAGA","available":"1"},
            {"id":"607","department":"13","name":"OPORAPA","available":"1"},
            {"id":"608","department":"13","name":"PAICOL","available":"1"},
            {"id":"609","department":"13","name":"PALERMO","available":"1"},
            {"id":"610","department":"13","name":"PALESTINA","available":"1"},
            {"id":"611","department":"13","name":"PITAL","available":"1"},
            {"id":"612","department":"13","name":"PITALITO","available":"1"},
            {"id":"613","department":"13","name":"RIVERA","available":"1"},
            {"id":"614","department":"13","name":"SALADOBLANCO","available":"1"},
            {"id":"615","department":"13","name":"SAN AGUSTIN","available":"1"},
            {"id":"616","department":"13","name":"SANTA MARIA","available":"1"},
            {"id":"617","department":"13","name":"SUAZA","available":"1"},
            {"id":"618","department":"13","name":"TARQUI","available":"1"},
            {"id":"619","department":"13","name":"TESALIA","available":"1"},
            {"id":"620","department":"13","name":"TELLO","available":"1"},
            {"id":"621","department":"13","name":"TERUEL","available":"1"},
            {"id":"622","department":"13","name":"TIMANA","available":"1"},
            {"id":"623","department":"13","name":"VILLAVIEJA","available":"1"},
            {"id":"624","department":"13","name":"YAGUARA","available":"1"},
            {"id":"625","department":"14","name":"RIOHACHA","available":"1"},
            {"id":"626","department":"14","name":"ALBANIA","available":"1"},
            {"id":"627","department":"14","name":"BARRANCAS","available":"1"},
            {"id":"628","department":"14","name":"DIBULLA","available":"1"},
            {"id":"629","department":"14","name":"DISTRACCION","available":"1"},
            {"id":"630","department":"14","name":"EL MOLINO","available":"1"},
            {"id":"631","department":"14","name":"FONSECA","available":"1"},
            {"id":"632","department":"14","name":"HATONUEVO","available":"1"},
            {"id":"633","department":"14","name":"LA JAGUA DEL PILAR","available":"1"},
            {"id":"634","department":"14","name":"MAICAO","available":"1"},
            {"id":"635","department":"14","name":"MANAURE","available":"1"},
            {"id":"636","department":"14","name":"SAN JUAN DEL CESAR","available":"1"},
            {"id":"637","department":"14","name":"URIBIA","available":"1"},
            {"id":"638","department":"14","name":"URUMITA","available":"1"},
            {"id":"639","department":"14","name":"VILLANUEVA","available":"1"},
            {"id":"640","department":"15","name":"SANTA MARTA","available":"1"},
            {"id":"641","department":"15","name":"ALGARROBO","available":"1"},
            {"id":"642","department":"15","name":"ARACATACA","available":"1"},
            {"id":"643","department":"15","name":"ARIGUANI","available":"1"},
            {"id":"644","department":"15","name":"CERRO SAN ANTONIO","available":"1"},
            {"id":"645","department":"15","name":"CHIBOLO","available":"1"},
            {"id":"646","department":"15","name":"CIENAGA","available":"1"},
            {"id":"647","department":"15","name":"CONCORDIA","available":"1"},
            {"id":"648","department":"15","name":"EL BANCO","available":"1"},
            {"id":"649","department":"15","name":"EL PIÑON","available":"1"},
            {"id":"650","department":"15","name":"EL RETEN","available":"1"},
            {"id":"651","department":"15","name":"FUNDACION","available":"1"},
            {"id":"652","department":"15","name":"GUAMAL","available":"1"},
            {"id":"653","department":"15","name":"NUEVA GRANADA","available":"1"},
            {"id":"654","department":"15","name":"PEDRAZA","available":"1"},
            {"id":"655","department":"15","name":"PIJIÑO DEL CARMEN","available":"1"},
            {"id":"656","department":"15","name":"PIVIJAY","available":"1"},
            {"id":"657","department":"15","name":"PLATO","available":"1"},
            {"id":"658","department":"15","name":"PUEBLOVIEJO","available":"1"},
            {"id":"659","department":"15","name":"REMOLINO","available":"1"},
            {"id":"660","department":"15","name":"SABANAS DE SAN ANGEL","available":"1"},
            {"id":"661","department":"15","name":"SALAMINA","available":"1"},
            {"id":"662","department":"15","name":"SAN SEBASTIAN DE BUENAVISTA","available":"1"},
            {"id":"663","department":"15","name":"SAN ZENON","available":"1"},
            {"id":"664","department":"15","name":"SANTA ANA","available":"1"},
            {"id":"665","department":"15","name":"SANTA BARBARA DE PINTO","available":"1"},
            {"id":"666","department":"15","name":"SITIONUEVO","available":"1"},
            {"id":"667","department":"15","name":"TENERIFE","available":"1"},
            {"id":"668","department":"15","name":"ZAPAYAN","available":"1"},
            {"id":"669","department":"15","name":"ZONA BANANERA","available":"1"},
            {"id":"670","department":"16","name":"VILLAVICENCIO","available":"1"},
            {"id":"671","department":"16","name":"ACACIAS","available":"1"},
            {"id":"672","department":"16","name":"BARRANCA DE UPIA","available":"1"},
            {"id":"673","department":"16","name":"CABUYARO","available":"1"},
            {"id":"674","department":"16","name":"CASTILLA LA NUEVA","available":"1"},
            {"id":"675","department":"16","name":"CUBARRAL","available":"1"},
            {"id":"676","department":"16","name":"CUMARAL","available":"1"},
            {"id":"677","department":"16","name":"EL CALVARIO","available":"1"},
            {"id":"678","department":"16","name":"EL CASTILLO","available":"1"},
            {"id":"679","department":"16","name":"EL DORADO","available":"1"},
            {"id":"680","department":"16","name":"FUENTE DE ORO","available":"1"},
            {"id":"681","department":"16","name":"GRANADA","available":"1"},
            {"id":"682","department":"16","name":"GUAMAL","available":"1"},
            {"id":"683","department":"16","name":"MAPIRIPAN","available":"1"},
            {"id":"684","department":"16","name":"MESETAS","available":"1"},
            {"id":"685","department":"16","name":"LA MACARENA","available":"1"},
            {"id":"686","department":"16","name":"URIBE","available":"1"},
            {"id":"687","department":"16","name":"LEJANIAS","available":"1"},
            {"id":"688","department":"16","name":"PUERTO CONCORDIA","available":"1"},
            {"id":"689","department":"16","name":"PUERTO GAITAN","available":"1"},
            {"id":"690","department":"16","name":"PUERTO LOPEZ","available":"1"},
            {"id":"691","department":"16","name":"PUERTO LLERAS","available":"1"},
            {"id":"692","department":"16","name":"PUERTO RICO","available":"1"},
            {"id":"693","department":"16","name":"RESTREPO","available":"1"},
            {"id":"694","department":"16","name":"SAN CARLOS DE GUAROA","available":"1"},
            {"id":"695","department":"16","name":"SAN JUAN DE ARAMA","available":"1"},
            {"id":"696","department":"16","name":"SAN JUANITO","available":"1"},
            {"id":"697","department":"16","name":"SAN MARTIN","available":"1"},
            {"id":"698","department":"16","name":"VISTAHERMOSA","available":"1"},
            {"id":"704","department":"17","name":"PASTO","available":"1"},
            {"id":"705","department":"17","name":"ALBAN","available":"1"},
            {"id":"706","department":"17","name":"ALDANA","available":"1"},
            {"id":"707","department":"17","name":"ANCUYA","available":"1"},
            {"id":"708","department":"17","name":"ARBOLEDA","available":"1"},
            {"id":"709","department":"17","name":"BARBACOAS","available":"1"},
            {"id":"710","department":"17","name":"BELEN","available":"1"},
            {"id":"711","department":"17","name":"BUESACO","available":"1"},
            {"id":"712","department":"17","name":"COLON","available":"1"},
            {"id":"713","department":"17","name":"CONSACA","available":"1"},
            {"id":"714","department":"17","name":"CONTADERO","available":"1"},
            {"id":"715","department":"17","name":"CORDOBA","available":"1"},
            {"id":"716","department":"17","name":"CUASPUD","available":"1"},
            {"id":"717","department":"17","name":"CUMBAL","available":"1"},
            {"id":"718","department":"17","name":"CUMBITARA","available":"1"},
            {"id":"719","department":"17","name":"CHACHAGsI","available":"1"},
            {"id":"720","department":"17","name":"EL CHARCO","available":"1"},
            {"id":"721","department":"17","name":"EL PEÑOL","available":"1"},
            {"id":"722","department":"17","name":"EL ROSARIO","available":"1"},
            {"id":"723","department":"17","name":"EL TABLON DE GOMEZ","available":"1"},
            {"id":"724","department":"17","name":"EL TAMBO","available":"1"},
            {"id":"725","department":"17","name":"FUNES","available":"1"},
            {"id":"726","department":"17","name":"GUACHUCAL","available":"1"},
            {"id":"727","department":"17","name":"GUAITARILLA","available":"1"},
            {"id":"728","department":"17","name":"GUALMATAN","available":"1"},
            {"id":"729","department":"17","name":"ILES","available":"1"},
            {"id":"730","department":"17","name":"IMUES","available":"1"},
            {"id":"731","department":"17","name":"IPIALES","available":"1"},
            {"id":"732","department":"17","name":"LA CRUZ","available":"1"},
            {"id":"733","department":"17","name":"LA FLORIDA","available":"1"},
            {"id":"734","department":"17","name":"LA LLANADA","available":"1"},
            {"id":"735","department":"17","name":"LA TOLA","available":"1"},
            {"id":"736","department":"17","name":"LA UNION","available":"1"},
            {"id":"737","department":"17","name":"LEIVA","available":"1"},
            {"id":"738","department":"17","name":"LINARES","available":"1"},
            {"id":"739","department":"17","name":"LOS ANDES","available":"1"},
            {"id":"740","department":"17","name":"MAGsI","available":"1"},
            {"id":"741","department":"17","name":"MALLAMA","available":"1"},
            {"id":"742","department":"17","name":"MOSQUERA","available":"1"},
            {"id":"743","department":"17","name":"NARIÑO","available":"1"},
            {"id":"744","department":"17","name":"OLAYA HERRERA","available":"1"},
            {"id":"745","department":"17","name":"OSPINA","available":"1"},
            {"id":"746","department":"17","name":"FRANCISCO PIZARRO","available":"1"},
            {"id":"747","department":"17","name":"POLICARPA","available":"1"},
            {"id":"748","department":"17","name":"POTOSI","available":"1"},
            {"id":"749","department":"17","name":"PROVIDENCIA","available":"1"},
            {"id":"750","department":"17","name":"PUERRES","available":"1"},
            {"id":"751","department":"17","name":"PUPIALES","available":"1"},
            {"id":"752","department":"17","name":"RICAURTE","available":"1"},
            {"id":"753","department":"17","name":"ROBERTO PAYAN","available":"1"},
            {"id":"754","department":"17","name":"SAMANIEGO","available":"1"},
            {"id":"755","department":"17","name":"SANDONA","available":"1"},
            {"id":"756","department":"17","name":"SAN BERNARDO","available":"1"},
            {"id":"757","department":"17","name":"SAN LORENZO","available":"1"},
            {"id":"758","department":"17","name":"SAN PABLO","available":"1"},
            {"id":"759","department":"17","name":"SAN PEDRO DE CARTAGO","available":"1"},
            {"id":"760","department":"17","name":"SANTA BARBARA","available":"1"},
            {"id":"761","department":"17","name":"SANTACRUZ","available":"1"},
            {"id":"762","department":"17","name":"SAPUYES","available":"1"},
            {"id":"763","department":"17","name":"TAMINANGO","available":"1"},
            {"id":"764","department":"17","name":"TANGUA","available":"1"},
            {"id":"765","department":"17","name":"SAN ANDRES DE TUMACO","available":"1"},
            {"id":"766","department":"17","name":"TUQUERRES","available":"1"},
            {"id":"767","department":"17","name":"YACUANQUER","available":"1"},
            {"id":"770","department":"18","name":"CUCUTA","available":"1"},
            {"id":"771","department":"18","name":"ABREGO","available":"1"},
            {"id":"772","department":"18","name":"ARBOLEDAS","available":"1"},
            {"id":"773","department":"18","name":"BOCHALEMA","available":"1"},
            {"id":"774","department":"18","name":"BUCARASICA","available":"1"},
            {"id":"775","department":"18","name":"CACOTA","available":"1"},
            {"id":"776","department":"18","name":"CACHIRA","available":"1"},
            {"id":"777","department":"18","name":"CHINACOTA","available":"1"},
            {"id":"778","department":"18","name":"CHITAGA","available":"1"},
            {"id":"779","department":"18","name":"CONVENCION","available":"1"},
            {"id":"780","department":"18","name":"CUCUTILLA","available":"1"},
            {"id":"781","department":"18","name":"DURANIA","available":"1"},
            {"id":"782","department":"18","name":"EL CARMEN","available":"1"},
            {"id":"783","department":"18","name":"EL TARRA","available":"1"},
            {"id":"784","department":"18","name":"EL ZULIA","available":"1"},
            {"id":"785","department":"18","name":"GRAMALOTE","available":"1"},
            {"id":"786","department":"18","name":"HACARI","available":"1"},
            {"id":"787","department":"18","name":"HERRAN","available":"1"},
            {"id":"788","department":"18","name":"LABATECA","available":"1"},
            {"id":"789","department":"18","name":"LA ESPERANZA","available":"1"},
            {"id":"790","department":"18","name":"LA PLAYA","available":"1"},
            {"id":"791","department":"18","name":"LOS PATIOS","available":"1"},
            {"id":"792","department":"18","name":"LOURDES","available":"1"},
            {"id":"793","department":"18","name":"MUTISCUA","available":"1"},
            {"id":"794","department":"18","name":"OCAÑA","available":"1"},
            {"id":"795","department":"18","name":"PAMPLONA","available":"1"},
            {"id":"796","department":"18","name":"PAMPLONITA","available":"1"},
            {"id":"797","department":"18","name":"PUERTO SANTANDER","available":"1"},
            {"id":"798","department":"18","name":"RAGONVALIA","available":"1"},
            {"id":"799","department":"18","name":"SALAZAR","available":"1"},
            {"id":"800","department":"18","name":"SAN CALIXTO","available":"1"},
            {"id":"801","department":"18","name":"SAN CAYETANO","available":"1"},
            {"id":"802","department":"18","name":"SANTIAGO","available":"1"},
            {"id":"803","department":"18","name":"SARDINATA","available":"1"},
            {"id":"804","department":"18","name":"SILOS","available":"1"},
            {"id":"805","department":"18","name":"TEORAMA","available":"1"},
            {"id":"806","department":"18","name":"TIBU","available":"1"},
            {"id":"807","department":"18","name":"TOLEDO","available":"1"},
            {"id":"808","department":"18","name":"VILLA CARO","available":"1"},
            {"id":"809","department":"18","name":"VILLA DEL ROSARIO","available":"1"},
            {"id":"810","department":"19","name":"ARMENIA","available":"1"},
            {"id":"811","department":"19","name":"BUENAVISTA","available":"1"},
            {"id":"812","department":"19","name":"CALARCA","available":"1"},
            {"id":"813","department":"19","name":"CIRCASIA","available":"1"},
            {"id":"814","department":"19","name":"CORDOBA","available":"1"},
            {"id":"815","department":"19","name":"FILANDIA","available":"1"},
            {"id":"816","department":"19","name":"GENOVA","available":"1"},
            {"id":"817","department":"19","name":"LA TEBAIDA","available":"1"},
            {"id":"818","department":"19","name":"MONTENEGRO","available":"1"},
            {"id":"819","department":"19","name":"PIJAO","available":"1"},
            {"id":"820","department":"19","name":"QUIMBAYA","available":"1"},
            {"id":"821","department":"19","name":"SALENTO","available":"1"},
            {"id":"822","department":"20","name":"PEREIRA","available":"1"},
            {"id":"823","department":"20","name":"APIA","available":"1"},
            {"id":"824","department":"20","name":"BALBOA","available":"1"},
            {"id":"825","department":"20","name":"BELEN DE UMBRIA","available":"1"},
            {"id":"826","department":"20","name":"DOSQUEBRADAS","available":"1"},
            {"id":"827","department":"20","name":"GUATICA","available":"1"},
            {"id":"828","department":"20","name":"LA CELIA","available":"1"},
            {"id":"829","department":"20","name":"LA VIRGINIA","available":"1"},
            {"id":"830","department":"20","name":"MARSELLA","available":"1"},
            {"id":"831","department":"20","name":"MISTRATO","available":"1"},
            {"id":"832","department":"20","name":"PUEBLO RICO","available":"1"},
            {"id":"833","department":"20","name":"QUINCHIA","available":"1"},
            {"id":"834","department":"20","name":"SANTA ROSA DE CABAL","available":"1"},
            {"id":"835","department":"20","name":"SANTUARIO","available":"1"},
            {"id":"837","department":"21","name":"BUCARAMANGA","available":"1"},
            {"id":"838","department":"21","name":"AGUADA","available":"1"},
            {"id":"839","department":"21","name":"ALBANIA","available":"1"},
            {"id":"840","department":"21","name":"ARATOCA","available":"1"},
            {"id":"841","department":"21","name":"BARBOSA","available":"1"},
            {"id":"842","department":"21","name":"BARICHARA","available":"1"},
            {"id":"843","department":"21","name":"BARRANCABERMEJA","available":"1"},
            {"id":"844","department":"21","name":"BETULIA","available":"1"},
            {"id":"845","department":"21","name":"BOLIVAR","available":"1"},
            {"id":"846","department":"21","name":"CABRERA","available":"1"},
            {"id":"847","department":"21","name":"CALIFORNIA","available":"1"},
            {"id":"848","department":"21","name":"CAPITANEJO","available":"1"},
            {"id":"849","department":"21","name":"CARCASI","available":"1"},
            {"id":"850","department":"21","name":"CEPITA","available":"1"},
            {"id":"851","department":"21","name":"CERRITO","available":"1"},
            {"id":"852","department":"21","name":"CHARALA","available":"1"},
            {"id":"853","department":"21","name":"CHARTA","available":"1"},
            {"id":"854","department":"21","name":"CHIMA","available":"1"},
            {"id":"855","department":"21","name":"CHIPATA","available":"1"},
            {"id":"856","department":"21","name":"CIMITARRA","available":"1"},
            {"id":"857","department":"21","name":"CONCEPCION","available":"1"},
            {"id":"858","department":"21","name":"CONFINES","available":"1"},
            {"id":"859","department":"21","name":"CONTRATACION","available":"1"},
            {"id":"860","department":"21","name":"COROMORO","available":"1"},
            {"id":"861","department":"21","name":"CURITI","available":"1"},
            {"id":"862","department":"21","name":"EL CARMEN DE CHUCURI","available":"1"},
            {"id":"863","department":"21","name":"EL GUACAMAYO","available":"1"},
            {"id":"864","department":"21","name":"EL PEÑON","available":"1"},
            {"id":"865","department":"21","name":"EL PLAYON","available":"1"},
            {"id":"866","department":"21","name":"ENCINO","available":"1"},
            {"id":"867","department":"21","name":"ENCISO","available":"1"},
            {"id":"868","department":"21","name":"FLORIAN","available":"1"},
            {"id":"869","department":"21","name":"FLORIDABLANCA","available":"1"},
            {"id":"870","department":"21","name":"GALAN","available":"1"},
            {"id":"871","department":"21","name":"GAMBITA","available":"1"},
            {"id":"872","department":"21","name":"GIRON","available":"1"},
            {"id":"873","department":"21","name":"GUACA","available":"1"},
            {"id":"874","department":"21","name":"GUADALUPE","available":"1"},
            {"id":"875","department":"21","name":"GUAPOTA","available":"1"},
            {"id":"876","department":"21","name":"GUAVATA","available":"1"},
            {"id":"877","department":"21","name":"GsEPSA","available":"1"},
            {"id":"878","department":"21","name":"HATO","available":"1"},
            {"id":"879","department":"21","name":"JESUS MARIA","available":"1"},
            {"id":"880","department":"21","name":"JORDAN","available":"1"},
            {"id":"881","department":"21","name":"LA BELLEZA","available":"1"},
            {"id":"882","department":"21","name":"LANDAZURI","available":"1"},
            {"id":"883","department":"21","name":"LA PAZ","available":"1"},
            {"id":"884","department":"21","name":"LEBRIJA","available":"1"},
            {"id":"885","department":"21","name":"LOS SANTOS","available":"1"},
            {"id":"886","department":"21","name":"MACARAVITA","available":"1"},
            {"id":"887","department":"21","name":"MALAGA","available":"1"},
            {"id":"888","department":"21","name":"MATANZA","available":"1"},
            {"id":"889","department":"21","name":"MOGOTES","available":"1"},
            {"id":"890","department":"21","name":"MOLAGAVITA","available":"1"},
            {"id":"891","department":"21","name":"OCAMONTE","available":"1"},
            {"id":"892","department":"21","name":"OIBA","available":"1"},
            {"id":"893","department":"21","name":"ONZAGA","available":"1"},
            {"id":"894","department":"21","name":"PALMAR","available":"1"},
            {"id":"895","department":"21","name":"PALMAS DEL SOCORRO","available":"1"},
            {"id":"896","department":"21","name":"PARAMO","available":"1"},
            {"id":"897","department":"21","name":"PIEDECUESTA","available":"1"},
            {"id":"898","department":"21","name":"PINCHOTE","available":"1"},
            {"id":"899","department":"21","name":"PUENTE NACIONAL","available":"1"},
            {"id":"900","department":"21","name":"PUERTO PARRA","available":"1"},
            {"id":"901","department":"21","name":"PUERTO WILCHES","available":"1"},
            {"id":"902","department":"21","name":"RIONEGRO","available":"1"},
            {"id":"903","department":"21","name":"SABANA DE TORRES","available":"1"},
            {"id":"904","department":"21","name":"SAN ANDRES","available":"1"},
            {"id":"905","department":"21","name":"SAN BENITO","available":"1"},
            {"id":"906","department":"21","name":"SAN GIL","available":"1"},
            {"id":"907","department":"21","name":"SAN JOAQUIN","available":"1"},
            {"id":"908","department":"21","name":"SAN JOSE DE MIRANDA","available":"1"},
            {"id":"909","department":"21","name":"SAN MIGUEL","available":"1"},
            {"id":"910","department":"21","name":"SAN VICENTE DE CHUCURI","available":"1"},
            {"id":"911","department":"21","name":"SANTA BARBARA","available":"1"},
            {"id":"912","department":"21","name":"SANTA HELENA DEL OPON","available":"1"},
            {"id":"913","department":"21","name":"SIMACOTA","available":"1"},
            {"id":"914","department":"21","name":"SOCORRO","available":"1"},
            {"id":"915","department":"21","name":"SUAITA","available":"1"},
            {"id":"916","department":"21","name":"SUCRE","available":"1"},
            {"id":"917","department":"21","name":"SURATA","available":"1"},
            {"id":"918","department":"21","name":"TONA","available":"1"},
            {"id":"919","department":"21","name":"VALLE DE SAN JOSE","available":"1"},
            {"id":"920","department":"21","name":"VELEZ","available":"1"},
            {"id":"921","department":"21","name":"VETAS","available":"1"},
            {"id":"922","department":"21","name":"VILLANUEVA","available":"1"},
            {"id":"923","department":"21","name":"ZAPATOCA","available":"1"},
            {"id":"924","department":"22","name":"SINCELEJO","available":"1"},
            {"id":"925","department":"22","name":"BUENAVISTA","available":"1"},
            {"id":"926","department":"22","name":"CAIMITO","available":"1"},
            {"id":"927","department":"22","name":"COLOSO","available":"1"},
            {"id":"928","department":"22","name":"COROZAL","available":"1"},
            {"id":"929","department":"22","name":"COVEÑAS","available":"1"},
            {"id":"930","department":"22","name":"CHALAN","available":"1"},
            {"id":"931","department":"22","name":"EL ROBLE","available":"1"},
            {"id":"932","department":"22","name":"GALERAS","available":"1"},
            {"id":"933","department":"22","name":"GUARANDA","available":"1"},
            {"id":"934","department":"22","name":"LA UNION","available":"1"},
            {"id":"935","department":"22","name":"LOS PALMITOS","available":"1"},
            {"id":"936","department":"22","name":"MAJAGUAL","available":"1"},
            {"id":"937","department":"22","name":"MORROA","available":"1"},
            {"id":"938","department":"22","name":"OVEJAS","available":"1"},
            {"id":"939","department":"22","name":"PALMITO","available":"1"},
            {"id":"940","department":"22","name":"SAMPUES","available":"1"},
            {"id":"941","department":"22","name":"SAN BENITO ABAD","available":"1"},
            {"id":"942","department":"22","name":"SAN JUAN DE BETULIA","available":"1"},
            {"id":"943","department":"22","name":"SAN MARCOS","available":"1"},
            {"id":"944","department":"22","name":"SAN ONOFRE","available":"1"},
            {"id":"945","department":"22","name":"SAN PEDRO","available":"1"},
            {"id":"946","department":"22","name":"SAN LUIS DE SINCE","available":"1"},
            {"id":"947","department":"22","name":"SUCRE","available":"1"},
            {"id":"948","department":"22","name":"SANTIAGO DE TOLU","available":"1"},
            {"id":"949","department":"22","name":"TOLU VIEJO","available":"1"},
            {"id":"953","department":"23","name":"IBAGUE","available":"1"},
            {"id":"954","department":"23","name":"ALPUJARRA","available":"1"},
            {"id":"955","department":"23","name":"ALVARADO","available":"1"},
            {"id":"956","department":"23","name":"AMBALEMA","available":"1"},
            {"id":"957","department":"23","name":"ANZOATEGUI","available":"1"},
            {"id":"958","department":"23","name":"ARMERO","available":"1"},
            {"id":"959","department":"23","name":"ATACO","available":"1"},
            {"id":"960","department":"23","name":"CAJAMARCA","available":"1"},
            {"id":"961","department":"23","name":"CARMEN DE APICALA","available":"1"},
            {"id":"962","department":"23","name":"CASABIANCA","available":"1"},
            {"id":"963","department":"23","name":"CHAPARRAL","available":"1"},
            {"id":"964","department":"23","name":"COELLO","available":"1"},
            {"id":"965","department":"23","name":"COYAIMA","available":"1"},
            {"id":"966","department":"23","name":"CUNDAY","available":"1"},
            {"id":"967","department":"23","name":"DOLORES","available":"1"},
            {"id":"968","department":"23","name":"ESPINAL","available":"1"},
            {"id":"969","department":"23","name":"FALAN","available":"1"},
            {"id":"970","department":"23","name":"FLANDES","available":"1"},
            {"id":"971","department":"23","name":"FRESNO","available":"1"},
            {"id":"972","department":"23","name":"GUAMO","available":"1"},
            {"id":"973","department":"23","name":"HERVEO","available":"1"},
            {"id":"974","department":"23","name":"HONDA","available":"1"},
            {"id":"975","department":"23","name":"ICONONZO","available":"1"},
            {"id":"976","department":"23","name":"LERIDA","available":"1"},
            {"id":"977","department":"23","name":"LIBANO","available":"1"},
            {"id":"978","department":"23","name":"MARIQUITA","available":"1"},
            {"id":"979","department":"23","name":"MELGAR","available":"1"},
            {"id":"980","department":"23","name":"MURILLO","available":"1"},
            {"id":"981","department":"23","name":"NATAGAIMA","available":"1"},
            {"id":"982","department":"23","name":"ORTEGA","available":"1"},
            {"id":"983","department":"23","name":"PALOCABILDO","available":"1"},
            {"id":"984","department":"23","name":"PIEDRAS","available":"1"},
            {"id":"985","department":"23","name":"PLANADAS","available":"1"},
            {"id":"986","department":"23","name":"PRADO","available":"1"},
            {"id":"987","department":"23","name":"PURIFICACION","available":"1"},
            {"id":"988","department":"23","name":"RIOBLANCO","available":"1"},
            {"id":"989","department":"23","name":"RONCESVALLES","available":"1"},
            {"id":"990","department":"23","name":"ROVIRA","available":"1"},
            {"id":"991","department":"23","name":"SALDAÑA","available":"1"},
            {"id":"992","department":"23","name":"SAN ANTONIO","available":"1"},
            {"id":"993","department":"23","name":"SAN LUIS","available":"1"},
            {"id":"994","department":"23","name":"SANTA ISABEL","available":"1"},
            {"id":"995","department":"23","name":"SUAREZ","available":"1"},
            {"id":"996","department":"23","name":"VALLE DE SAN JUAN","available":"1"},
            {"id":"997","department":"23","name":"VENADILLO","available":"1"},
            {"id":"998","department":"23","name":"VILLAHERMOSA","available":"1"},
            {"id":"999","department":"23","name":"VILLARRICA","available":"1"},
            {"id":"1002","department":"24","name":"CALI","available":"1"},
            {"id":"1003","department":"24","name":"ALCALA","available":"1"},
            {"id":"1004","department":"24","name":"ANDALUCIA","available":"1"},
            {"id":"1005","department":"24","name":"ANSERMANUEVO","available":"1"},
            {"id":"1006","department":"24","name":"ARGELIA","available":"1"},
            {"id":"1007","department":"24","name":"BOLIVAR","available":"1"},
            {"id":"1008","department":"24","name":"BUENAVENTURA","available":"1"},
            {"id":"1009","department":"24","name":"GUADALAJARA DE BUGA","available":"1"},
            {"id":"1010","department":"24","name":"BUGALAGRANDE","available":"1"},
            {"id":"1011","department":"24","name":"CAICEDONIA","available":"1"},
            {"id":"1012","department":"24","name":"CALIMA","available":"1"},
            {"id":"1013","department":"24","name":"CANDELARIA","available":"1"},
            {"id":"1014","department":"24","name":"CARTAGO","available":"1"},
            {"id":"1015","department":"24","name":"DAGUA","available":"1"},
            {"id":"1016","department":"24","name":"EL AGUILA","available":"1"},
            {"id":"1017","department":"24","name":"EL CAIRO","available":"1"},
            {"id":"1018","department":"24","name":"EL CERRITO","available":"1"},
            {"id":"1019","department":"24","name":"EL DOVIO","available":"1"},
            {"id":"1020","department":"24","name":"FLORIDA","available":"1"},
            {"id":"1021","department":"24","name":"GINEBRA","available":"1"},
            {"id":"1022","department":"24","name":"GUACARI","available":"1"},
            {"id":"1023","department":"24","name":"JAMUNDI","available":"1"},
            {"id":"1024","department":"24","name":"LA CUMBRE","available":"1"},
            {"id":"1025","department":"24","name":"LA UNION","available":"1"},
            {"id":"1026","department":"24","name":"LA VICTORIA","available":"1"},
            {"id":"1027","department":"24","name":"OBANDO","available":"1"},
            {"id":"1028","department":"24","name":"PALMIRA","available":"1"},
            {"id":"1029","department":"24","name":"PRADERA","available":"1"},
            {"id":"1030","department":"24","name":"RESTREPO","available":"1"},
            {"id":"1031","department":"24","name":"RIOFRIO","available":"1"},
            {"id":"1032","department":"24","name":"ROLDANILLO","available":"1"},
            {"id":"1033","department":"24","name":"SAN PEDRO","available":"1"},
            {"id":"1034","department":"24","name":"SEVILLA","available":"1"},
            {"id":"1035","department":"24","name":"TORO","available":"1"},
            {"id":"1036","department":"24","name":"TRUJILLO","available":"1"},
            {"id":"1037","department":"24","name":"TULUA","available":"1"},
            {"id":"1038","department":"24","name":"ULLOA","available":"1"},
            {"id":"1039","department":"24","name":"VERSALLES","available":"1"},
            {"id":"1040","department":"24","name":"VIJES","available":"1"},
            {"id":"1041","department":"24","name":"YOTOCO","available":"1"},
            {"id":"1042","department":"24","name":"YUMBO","available":"1"},
            {"id":"1043","department":"24","name":"ZARZAL","available":"1"},
            {"id":"1044","department":"25","name":"ARAUCA","available":"1"},
            {"id":"1045","department":"25","name":"ARAUQUITA","available":"1"},
            {"id":"1046","department":"25","name":"CRAVO NORTE","available":"1"},
            {"id":"1047","department":"25","name":"FORTUL","available":"1"},
            {"id":"1048","department":"25","name":"PUERTO RONDON","available":"1"},
            {"id":"1049","department":"25","name":"SARAVENA","available":"1"},
            {"id":"1050","department":"25","name":"TAME","available":"1"},
            {"id":"1051","department":"26","name":"AGUAZUL","available":"1"},
            {"id":"1052","department":"26","name":"CHAMEZA","available":"1"},
            {"id":"1053","department":"26","name":"HATO COROZAL","available":"1"},
            {"id":"1054","department":"26","name":"LA SALINA","available":"1"},
            {"id":"1055","department":"26","name":"MANI","available":"1"},
            {"id":"1056","department":"26","name":"MONTERREY","available":"1"},
            {"id":"1057","department":"26","name":"NUNCHIA","available":"1"},
            {"id":"1058","department":"26","name":"OROCUE","available":"1"},
            {"id":"1059","department":"26","name":"PAZ DE ARIPORO","available":"1"},
            {"id":"1060","department":"26","name":"PORE","available":"1"},
            {"id":"1061","department":"26","name":"RECETOR","available":"1"},
            {"id":"1062","department":"26","name":"SABANALARGA","available":"1"},
            {"id":"1063","department":"26","name":"SACAMA","available":"1"},
            {"id":"1064","department":"26","name":"SAN LUIS DE PALENQUE","available":"1"},
            {"id":"1065","department":"26","name":"TAMARA","available":"1"},
            {"id":"1066","department":"26","name":"TAURAMENA","available":"1"},
            {"id":"1067","department":"26","name":"TRINIDAD","available":"1"},
            {"id":"1068","department":"26","name":"VILLANUEVA","available":"1"},
            {"id":"1069","department":"26","name":"YOPAL","available":"1"},
            {"id":"1070","department":"27","name":"MOCOA","available":"1"},
            {"id":"1071","department":"27","name":"COLON","available":"1"},
            {"id":"1072","department":"27","name":"ORITO","available":"1"},
            {"id":"1073","department":"27","name":"PUERTO ASIS","available":"1"},
            {"id":"1074","department":"27","name":"PUERTO CAICEDO","available":"1"},
            {"id":"1075","department":"27","name":"PUERTO GUZMAN","available":"1"},
            {"id":"1076","department":"27","name":"LEGUIZAMO","available":"1"},
            {"id":"1077","department":"27","name":"SIBUNDOY","available":"1"},
            {"id":"1078","department":"27","name":"SAN FRANCISCO","available":"1"},
            {"id":"1079","department":"27","name":"SAN MIGUEL","available":"1"},
            {"id":"1080","department":"27","name":"SANTIAGO","available":"1"},
            {"id":"1081","department":"27","name":"VALLE DEL GUAMUEZ","available":"1"},
            {"id":"1082","department":"27","name":"VILLAGARZON","available":"1"},
            {"id":"1083","department":"28","name":"SAN ANDRES","available":"1"},
            {"id":"1084","department":"28","name":"PROVIDENCIA","available":"1"},
            {"id":"1085","department":"29","name":"LETICIA","available":"1"},
            {"id":"1086","department":"29","name":"EL ENCANTO","available":"1"},
            {"id":"1087","department":"29","name":"LA CHORRERA","available":"1"},
            {"id":"1088","department":"29","name":"LA PEDRERA","available":"1"},
            {"id":"1089","department":"29","name":"LA VICTORIA","available":"1"},
            {"id":"1090","department":"29","name":"MIRITI - PARANA","available":"1"},
            {"id":"1091","department":"29","name":"PUERTO ALEGRIA","available":"1"},
            {"id":"1092","department":"29","name":"PUERTO ARICA","available":"1"},
            {"id":"1093","department":"29","name":"PUERTO NARIÑO","available":"1"},
            {"id":"1094","department":"29","name":"PUERTO SANTANDER","available":"1"},
            {"id":"1095","department":"29","name":"TARAPACA","available":"1"},
            {"id":"1096","department":"30","name":"INIRIDA","available":"1"},
            {"id":"1097","department":"30","name":"BARRANCO MINAS","available":"1"},
            {"id":"1098","department":"30","name":"MAPIRIPANA","available":"1"},
            {"id":"1099","department":"30","name":"SAN FELIPE","available":"1"},
            {"id":"1100","department":"30","name":"PUERTO COLOMBIA","available":"1"},
            {"id":"1101","department":"30","name":"LA GUADALUPE","available":"1"},
            {"id":"1102","department":"30","name":"CACAHUAL","available":"1"},
            {"id":"1103","department":"30","name":"PANA PANA","available":"1"},
            {"id":"1104","department":"30","name":"MORICHAL","available":"1"},
            {"id":"1105","department":"31","name":"SAN JOSE DEL GUAVIARE","available":"1"},
            {"id":"1106","department":"31","name":"CALAMAR","available":"1"},
            {"id":"1107","department":"31","name":"EL RETORNO","available":"1"},
            {"id":"1108","department":"31","name":"MIRAFLORES","available":"1"},
            {"id":"1109","department":"32","name":"MITU","available":"1"},
            {"id":"1110","department":"32","name":"CARURU","available":"1"},
            {"id":"1111","department":"32","name":"PACOA","available":"1"},
            {"id":"1112","department":"32","name":"TARAIRA","available":"1"},
            {"id":"1113","department":"32","name":"PAPUNAUA","available":"1"},
            {"id":"1114","department":"32","name":"YAVARATE","available":"1"},
            {"id":"1115","department":"33","name":"PUERTO CARREÑO","available":"1"},
            {"id":"1116","department":"33","name":"LA PRIMAVERA","available":"1"},
            {"id":"1117","department":"33","name":"SANTA ROSALIA","available":"1"},
            {"id":"1118","department":"33","name":"CUMARIBO","available":"1"}
            ]
            ';

        foreach (json_decode($data) as $key => $value) {
            Citie::create([
                'id' => $value->id,
                'department_id' => $value->department,
                'name' => $value->name,
            ]);
        }

    }
}
