version: "3.3"

services:
  nginx:
    build:
      context: "./conf/nginx"
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    tty: true
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    network_mode: bridge

  php:
    build:
      context: "./conf/php"
    container_name: ${PROJECT_NAME}-php
    tty: true
    restart: always
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
    links:
      - mysql
    network_mode: bridge

  mysql:
    build:
      context: "./conf/mysql"
    container_name: ${PROJECT_NAME}-mysql
    restart: always
    tty: true
    volumes:
      - ${MYSQL_DATA}:/var/lib/mysql
    ports: 
      - "4002:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    network_mode: bridge
